[package]
description = "A Rust implementation of the Freeverb algorithm."
documentation = "https://docs.rs/freeverb"
edition = "2021"
license = "MIT"
name = "freeverb"
readme = "README.md"
repository = "https://github.com/trevyn/freeverb"
rust-version = "1.56"
version = "0.1.0"

[dependencies]
